alias st='git status'alias di='git diff --staged'alias co='git commit -m'alias ad='git add'alias ch='git checkout'alias pu='git push origin `git symbolic-ref --short HEAD`'alias dif='git diff'alias pull='git pull'alias gl='git log'alias ch='git checkout'alias reset='git reset --hard'alias rebase='git rebase -i'alias br='git branch'
alias fd='firebase deploy'
alias nb='npm run build'
alias ns='npm run serve'
alias fdf='firebase deploy --only functions'
alias fs='firebase serve'
alias nb8='nodebrew use v8.16.0'
alias nb10='nodebrew use v10.5.0'
alias fdh='firebase deploy --only hosting'
alias fdfo='firebase deploy --only'
